### ISSUE TITLE
Rules-

### ISSUE THREAD

**Issue by redstonemeg** [lynn/hello-wordl#79] opened 2022-02-05 21:30 UTC
you should not be able to use the same letter twice in one word (or if you do, you should reveal it when the first letter is guessed);
Old mastermind rules!

**Comment by lynn** [comment] 2022-02-09 15:51
Well, this game is not Mastermind — but I admit the exact workings of double letters are still a bit under-explained (although I promise they work _exactly_ the same way as in original Wordle). In that light, I'll close this as a duplicate of #75.

**Closed by lynn** 2022-02-09 15:51 UTC
